"""Windows numeric constants mapped to macOS named enumerators.

Generated by ``scripts/gen_mac_enums.py`` from PowerPoint's own AppleScript
dictionary. Do not edit by hand; regenerate instead, which is also how this
stays correct when Microsoft ships a new PowerPoint.

The pairing is done by name rather than by number, because the two platforms
only sometimes agree on the number. ``ppSaveAsPNG`` is 18 on Windows while
``save as PNG`` is 24 on macOS, and ``ppLayoutBlank`` is 12 on both.

397 constants across 40 enumerations, read from PowerPoint 16.97.2.

Windows constants this table does not carry, so that asking for one raises
rather than quietly resolving to something close. Most genuinely have no macOS
word. The four slide transitions have the opposite problem, each exists as four
directional variants and in no plain form, and picking one would be a guess:

    MsoAnimAfterEffect: msoAnimAfterEffectNone
    MsoAnimTriggerType: msoAnimTriggerNone
    MsoAnimateByLevel: msoAnimateLevelNone
    MsoShapeType: msoEmbeddedOLEObject, msoOLEControlObject, msoTextEffect
    MsoTextOrientation: msoTextOrientationVerticalFarEast
    MsoTriState: msoTriStateMixed
    MsoVerticalAnchor: msoVerticalAnchorMixed
    PpDateTimeFormat: ppDateTimeddddMMMMddyyyy, ppDateTimedMMMMyyyy, ppDateTimedMMMyy, ppDateTimeMddyy, ppDateTimehmmAMPM, ppDateTimehmmssAMPM
    PpEntryEffect: ppEffectPush, ppEffectWipe, ppEffectSplit, ppEffectReveal
    PpMediaType: ppMediaTypeMixed
    PpNumberedBulletStyle: ppBulletArabicDBPeriod
    PpPlaceholderType: ppPlaceholderMixed
    PpSaveAsFileType: ppSaveAsOpenXMLAddin, ppSaveAsXPS, ppSaveAsOpenDocumentPresentation, ppSaveAsWMV, ppSaveAsMP4
    PpSlideLayout: ppLayoutTextAndMediaClip, ppLayoutMixed
    PpTransitionSpeed: ppTransitionSpeedFast, ppTransitionSpeedMedium, ppTransitionSpeedSlow
    PpViewType: ppViewSlideMaster, ppViewNotesPage, ppViewThumbnails, ppViewMasterThumbnails
    PpWindowState: ppWindowMaximized
"""

from appscript import k


def to_keyword(table, value, what):
    """Translate a Windows constant, or say plainly that macOS has no word for it.

    A missing entry is not a bug in the table. Windows genuinely has constants
    PowerPoint for Mac never learned, and the useful thing is to name which one
    rather than to fall back to something close.
    """
    try:
        return table[value]
    except KeyError:
        raise ValueError(
            "PowerPoint for Mac has no %s matching the Windows constant %r"
            % (what, value)
        ) from None


MsoAnimAfterEffect: dict = {
    1: k.dim,  # msoAnimAfterEffectDim
    2: k.hide,  # msoAnimAfterEffectHide
    3: k.hide_on_next_click,  # msoAnimAfterEffectHideOnNextClick
}


MsoAnimDirection: dict = {
    0: k.no_direction,  # none
    1: k.up,  # up
    2: k.right,  # right
    3: k.down,  # down
    4: k.left,  # left
    6: k.up_left,  # up_left
    7: k.up_right,  # up_right
    8: k.down_right,  # down_right
    9: k.down_left,  # down_left
    10: k.top,  # top
    11: k.bottom,  # bottom
    12: k.top_left,  # top_left
    13: k.top_right,  # top_right
    14: k.bottom_right,  # bottom_right
    15: k.bottom_left,  # bottom_left
    16: k.horizontal,  # horizontal
    17: k.vertical,  # vertical
    18: k.across,  # across
    19: k.inward,  # in
    20: k.out,  # out
    21: k.clockwise,  # clockwise
    22: k.counterclockwise,  # counterclockwise
    23: k.horizontal_in,  # horizontal_in
    24: k.horizontal_out,  # horizontal_out
    25: k.vertical_in,  # vertical_in
    26: k.vertical_out,  # vertical_out
}


MsoAnimEffect: dict = {
    1: k.animation_type_appear,  # msoAnimEffectAppear
    2: k.animation_type_fly,  # msoAnimEffectFly
    3: k.animation_type_blinds,  # msoAnimEffectBlinds
    4: k.animation_type_box,  # msoAnimEffectBox
    5: k.animation_type_checkerboard,  # msoAnimEffectCheckerboard
    6: k.animation_type_circle,  # msoAnimEffectCircle
    8: k.animation_type_diamond,  # msoAnimEffectDiamond
    9: k.animation_type_dissolve,  # msoAnimEffectDissolve
    10: k.animation_type_fade,  # msoAnimEffectFade
    16: k.animation_type_split,  # msoAnimEffectSplit
    22: k.animation_type_wipe,  # msoAnimEffectWipe
    23: k.animation_type_zoom,  # msoAnimEffectZoom
    26: k.animation_type_bounce,  # msoAnimEffectBounce
    30: k.animation_type_float,  # msoAnimEffectFloat
    31: k.animation_type_grow_and_turn,  # msoAnimEffectGrowAndTurn
    54: k.animation_type_change_fill_color,  # change_fill_color
    55: k.animation_type_change_font,  # change_font
    56: k.animation_type_change_font_color,  # change_font_color
    57: k.animation_type_change_font_size,  # change_font_size
    59: k.animation_type_grow_shrink,  # grow_shrink
    61: k.animation_type_spin,  # msoAnimEffectSpin
    62: k.animation_type_transparency,  # msoAnimEffectTransparency
    63: k.animation_type_bold_flash,  # bold_flash
    69: k.animation_type_color_wave,  # color_wave
    73: k.animation_type_darken,  # darken
    74: k.animation_type_desaturate,  # desaturate
    75: k.animation_type_flash_bulb,  # flash_bulb
    78: k.animation_type_lighten,  # lighten
    80: k.animation_type_teeter,  # teeter
    82: k.animation_type_wave,  # wave
    86: k.animation_type_circle_path,  # path_circle
    88: k.animation_type_diamond_path,  # path_diamond
    90: k.animation_type_5_point_star_path,  # path_star
    92: k.animation_type_square_path,  # path_square
    94: k.animation_type_heart_path,  # path_heart
    109: k.animation_type_loop_de_loop_path,  # path_loop
    120: k.animation_type_left_path,  # path_left
    122: k.animation_type_arc_down_path,  # path_arc_down
    123: k.animation_type_zigzag_path,  # path_zigzag
    125: k.animation_type_sine_wave_path,  # path_sine_wave
    126: k.animation_type_bounce_left_path,  # path_bounce_left
    127: k.animation_type_down_path,  # path_down
    129: k.animation_type_arc_up_path,  # path_arc_up
    131: k.animation_type_spiral_right_path,  # path_spiral_right
    132: k.animation_type_wave_path,  # path_wave
    134: k.animation_type_diagonal_down_right_path,  # path_diagonal_down_right
    136: k.animation_type_arc_left_path,  # path_arc_left
    137: k.animation_type_funnel_path,  # path_funnel
    138: k.animation_type_spring_path,  # path_spring
    139: k.animation_type_bounce_right_path,  # path_bounce_right
    141: k.animation_type_diagonal_up_right_path,  # path_diagonal_up_right
    143: k.animation_type_arc_right_path,  # path_arc_right
    148: k.animation_type_up_path,  # path_up
    149: k.animation_type_right_path,  # path_right
}


MsoAnimTextUnitEffect: dict = {
    0: k.by_paragraph,  # msoAnimTextUnitEffectByParagraph
    1: k.by_character,  # msoAnimTextUnitEffectByCharacter
    2: k.by_word,  # msoAnimTextUnitEffectByWord
}


MsoAnimTriggerType: dict = {
    1: k.on_page_click,  # msoAnimTriggerOnPageClick
    2: k.with_previous,  # msoAnimTriggerWithPrevious
    3: k.after_previous,  # msoAnimTriggerAfterPrevious
    4: k.on_shape_click,  # msoAnimTriggerOnShapeClick
}


MsoAnimateByLevel: dict = {
    1: k.text_by_all_levels,  # msoAnimateTextByAllLevels
    2: k.text_by_first_level,  # msoAnimateTextByFirstLevel
    3: k.text_by_second_level,  # msoAnimateTextBySecondLevel
    4: k.text_by_third_level,  # msoAnimateTextByThirdLevel
    5: k.text_by_fourth_level,  # msoAnimateTextByFourthLevel
    6: k.text_by_fifth_level,  # msoAnimateTextByFifthLevel
}


MsoArrowheadStyle: dict = {
    1: k.no_arrowhead,  # msoArrowheadNone
    2: k.triangle_arrowhead,  # msoArrowheadTriangle
    3: k.open_arrowhead,  # msoArrowheadOpen
    4: k.stealth_arrowhead,  # msoArrowheadStealth
    5: k.diamond_arrowhead,  # msoArrowheadDiamond
    6: k.oval_arrowhead,  # msoArrowheadOval
}


MsoAutoShapeType: dict = {
    1: k.autoshape_rectangle,  # msoShapeRectangle
    2: k.autoshape_parallelogram,  # msoShapeParallelogram
    3: k.autoshape_trapezoid,  # msoShapeTrapezoid
    4: k.autoshape_diamond,  # msoShapeDiamond
    5: k.autoshape_rounded_rectangle,  # msoShapeRoundedRectangle
    6: k.autoshape_octagon,  # msoShapeOctagon
    7: k.autoshape_isosceles_triangle,  # msoShapeIsoscelesTriangle
    8: k.autoshape_right_triangle,  # msoShapeRightTriangle
    9: k.autoshape_oval,  # msoShapeOval
    10: k.autoshape_hexagon,  # msoShapeHexagon
    11: k.autoshape_cross,  # msoShapeCross
    12: k.autoshape_regular_pentagon,  # msoShapeRegularPentagon
    13: k.autoshape_can,  # msoShapeCan
    14: k.autoshape_cube,  # msoShapeCube
    17: k.autoshape_smiley_face,  # msoShapeSmileyFace
    18: k.autoshape_donut,  # msoShapeDonut
    19: k.autoshape_no_symbol,  # msoShapeNoSymbol
    20: k.autoshape_block_arc,  # block_arc
    21: k.autoshape_heart,  # msoShapeHeart
    22: k.autoshape_lightning_bolt,  # msoShapeLightningBolt
    23: k.autoshape_sun,  # msoShapeSun
    24: k.autoshape_moon,  # msoShapeMoon
    25: k.autoshape_arc,  # msoShapeArc
    26: k.autoshape_double_bracket,  # double_bracket
    27: k.autoshape_double_brace,  # double_brace
    29: k.autoshape_left_bracket,  # left_bracket
    30: k.autoshape_right_bracket,  # right_bracket
    31: k.autoshape_left_brace,  # left_brace
    32: k.autoshape_right_brace,  # right_brace
    33: k.autoshape_right_arrow,  # msoShapeRightArrow
    34: k.autoshape_left_arrow,  # msoShapeLeftArrow
    35: k.autoshape_up_arrow,  # msoShapeUpArrow
    36: k.autoshape_down_arrow,  # msoShapeDownArrow
    37: k.autoshape_left_right_arrow,  # msoShapeLeftRightArrow
    38: k.autoshape_up_down_arrow,  # msoShapeUpDownArrow
    39: k.autoshape_quad_arrow,  # msoShapeQuadArrow
    49: k.autoshape_striped_right_arrow,  # striped_right_arrow
    50: k.autoshape_notched_right_arrow,  # notched_right_arrow
    51: k.autoshape_pentagon,  # msoShapePentagon
    52: k.autoshape_chevron,  # msoShapeChevron
    61: k.autoshape_flowchart_process,  # msoShapeFlowchartProcess
    63: k.autoshape_flowchart_decision,  # msoShapeFlowchartDecision
    64: k.autoshape_flowchart_data,  # msoShapeFlowchartData
    67: k.autoshape_flowchart_document,  # msoShapeFlowchartDocument
    69: k.autoshape_flowchart_terminator,  # msoShapeFlowchartTerminator
    73: k.autoshape_flowchart_connector,  # msoShapeFlowchartConnector
    89: k.autoshape_explosion_one,  # msoShapeExplosion1
    90: k.autoshape_explosion_two,  # msoShapeExplosion2
    91: k.autoshape_four_point_star,  # msoShape4pointStar
    92: k.autoshape_five_point_star,  # msoShape5pointStar
    93: k.autoshape_eight_point_star,  # msoShape8pointStar
    94: k.autoshape_sixteen_point_star,  # msoShape16pointStar
    95: k.autoshape_twenty_four_point_star,  # msoShape24pointStar
    96: k.autoshape_thirty_two_point_star,  # msoShape32pointStar
    105: k.autoshape_rectangular_callout,  # rectangular_callout
    106: k.autoshape_rounded_rectangular_callout,  # rounded_rectangular_callout
    107: k.autoshape_oval_callout,  # oval_callout
    108: k.autoshape_cloud_callout,  # cloud_callout
    158: k.autoshape_frame,  # frame
    159: k.autoshape_half_frame,  # half_frame
    162: k.autoshape_corner,  # l_shape
    179: k.autoshape_cloud,  # msoShapeCloud
}


MsoConnectorType: dict = {
    1: k.straight,  # msoConnectorStraight
    2: k.elbow,  # msoConnectorElbow
    3: k.curve,  # msoConnectorCurve
}


MsoFillType: dict = {
    1: k.fill_solid,  # msoFillSolid
    2: k.fill_patterned,  # msoFillPatterned
    3: k.fill_gradient,  # msoFillGradient
    4: k.fill_textured,  # msoFillTextured
    5: k.fill_background,  # msoFillBackground
    6: k.fill_picture,  # msoFillPicture
}


MsoFlipCmd: dict = {
    0: k.flip_horizontal,  # msoFlipHorizontal
    1: k.flip_vertical,  # msoFlipVertical
}


MsoGradientStyle: dict = {
    1: k.horizontal_gradient,  # msoGradientHorizontal
    2: k.vertical_gradient,  # msoGradientVertical
    3: k.diagonal_up_gradient,  # msoGradientDiagonalUp
    4: k.diagonal_down_gradient,  # msoGradientDiagonalDown
    5: k.from_corner_gradient,  # msoGradientFromCorner
    7: k.from_center_gradient,  # msoGradientFromCenter
}


MsoLineDashStyle: dict = {
    1: k.line_dash_style_solid,  # msoLineSolid
    2: k.line_dash_style_round_dot,  # msoLineRoundDot
    3: k.line_dash_style_square_dot,  # msoLineDot
    4: k.line_dash_style_dash,  # msoLineDash
    5: k.line_dash_style_dash_dot,  # msoLineDashDot
    6: k.line_dash_style_dash_dot_dot,  # msoLineDashDotDot
    7: k.line_dash_style_long_dash,  # msoLineLongDash
    8: k.line_dash_style_long_dash_dot,  # msoLineLongDashDot
}


MsoPictureColorType: dict = {
    1: k.picture_color_automatic,  # msoPictureAutomatic
    2: k.picture_color_gray_scale,  # msoPictureGrayscale
    3: k.picture_color_black_and_white,  # msoPictureBlackAndWhite
    4: k.picture_color_watermark,  # msoPictureWatermark
}


MsoShapeType: dict = {
    1: k.shape_type_auto,  # msoAutoShape
    2: k.shape_type_callout,  # msoCallout
    3: k.shape_type_chart,  # msoChart
    4: k.shape_type_comment,  # msoComment
    5: k.shape_type_free_form,  # msoFreeform
    6: k.shape_type_group,  # msoGroup
    8: k.shape_type_form_control,  # msoFormControl
    9: k.shape_type_line,  # msoLine
    10: k.shape_type_linked_OLE_object,  # msoLinkedOLEObject
    11: k.shape_type_linked_picture,  # msoLinkedPicture
    13: k.shape_type_picture,  # msoPicture
    14: k.shape_type_place_holder,  # msoPlaceholder
    16: k.shape_type_media,  # msoMedia
    17: k.shape_type_text_box,  # msoTextBox
    19: k.shape_type_table,  # msoTable
    24: k.shape_type_smartart_graphic,  # msoSmartArt
}


MsoTextOrientation: dict = {
    1: k.horizontal,  # msoTextOrientationHorizontal
    2: k.upward,  # msoTextOrientationUpward
    3: k.downward,  # msoTextOrientationDownward
    5: k.vertical,  # msoTextOrientationVertical
}


MsoThemeColorIndex: dict = {
    1: k.first_dark_theme_color,  # msoThemeColorDark1
    2: k.first_light_theme_color,  # msoThemeColorLight1
    3: k.second_dark_theme_color,  # msoThemeColorDark2
    4: k.second_light_theme_color,  # msoThemeColorLight2
    5: k.first_accent_theme_color,  # msoThemeColorAccent1
    6: k.second_accent_theme_color,  # msoThemeColorAccent2
    7: k.third_accent_theme_color,  # msoThemeColorAccent3
    8: k.fourth_accent_theme_color,  # msoThemeColorAccent4
    9: k.fifth_accent_theme_color,  # msoThemeColorAccent5
    10: k.sixth_accent_theme_color,  # msoThemeColorAccent6
    11: k.hyperlink_theme_color,  # msoThemeColorHyperlink
    12: k.followed_hyperlink_theme_color,  # msoThemeColorFollowedHyperlink
}


MsoTriState: dict = {
    -3: k.toggle,  # msoTriStateToggle
    -1: k.true,  # msoTrue
    0: k.false,  # msoFalse
    1: k.C_true,  # msoCTrue
}


MsoVerticalAnchor: dict = {
    1: k.anchor_top,  # msoAnchorTop
    2: k.anchor_top_baseline,  # msoAnchorTopBaseline
    3: k.anchor_middle,  # msoAnchorMiddle
    4: k.anchor_bottom,  # msoAnchorBottom
    5: k.anchor_bottom_baseline,  # msoAnchorBottomBaseLine
}


MsoZOrderCmd: dict = {
    0: k.bring_shape_to_front,  # msoBringToFront
    1: k.send_shape_to_back,  # msoSendToBack
    2: k.bring_shape_forward,  # msoBringForward
    3: k.send_shape_backward,  # msoSendBackward
}


PpActionType: dict = {
    0: k.action_type_none,  # ppActionNone
    1: k.action_type_next_slide,  # ppActionNextSlide
    2: k.action_type_previous_slide,  # ppActionPreviousSlide
    3: k.action_type_first_slide,  # ppActionFirstSlide
    4: k.action_type_last_slide,  # ppActionLastSlide
    6: k.action_type_end_show,  # ppActionEndShow
    7: k.action_type_hyperlink_action,  # ppActionHyperlink
}


PpAutoSize: dict = {
    -2: k.ppAutoSizemixed,  # ppAutoSizeMixed
    0: k.ppAutoSizeNone,  # ppAutoSizeNone
    1: k.ppAutoSizeShapeToFitText,  # ppAutoSizeShapeToFitText
}


PpBorderType: dict = {
    1: k.top_border,  # ppBorderTop
    2: k.left_border,  # ppBorderLeft
    3: k.bottom_border,  # ppBorderBottom
    4: k.right_border,  # ppBorderRight
    5: k.diagonal_down_border,  # ppBorderDiagonalDown
    6: k.diagonal_up_border,  # ppBorderDiagonalUp
}


PpBulletType: dict = {
    0: k.ppBulletNone,  # ppBulletNone
    1: k.ppBulletUnnumbered,  # ppBulletUnnumbered
    2: k.ppBulletNumbered,  # ppBulletNumbered
    3: k.ppBulletPicture,  # ppBulletPicture
}


PpDateTimeFormat: dict = {
    1: k.Mdyy,  # ppDateTimeMdyy
    4: k.MMMMdyyyy,  # ppDateTimeMMMMdyyyy
    6: k.MMMMyy,  # ppDateTimeMMMMyy
    7: k.MMyy,  # ppDateTimeMMyy
    9: k.Hmm,  # ppDateTimeHmm
    10: k.Hmmss,  # ppDateTimeHmmss
}


PpEntryEffect: dict = {
    0: k.entry_effect_none,  # ppEffectNone
    257: k.entry_effect_cut,  # ppEffectCut
    513: k.entry_effect_random,  # ppEffectRandom
    769: k.entry_effect_blinds_horizontal,  # ppEffectBlindsHorizontal
    770: k.entry_effect_blinds_vertical,  # ppEffectBlindsVertical
    1537: k.entry_effect_dissolve,  # ppEffectDissolve
    3844: k.entry_effect_fade,  # ppEffectFade
}


PpMediaType: dict = {
    0: k.media_type_other,  # ppMediaTypeOther
    1: k.media_type_sound,  # ppMediaTypeSound
    3: k.media_type_movie,  # ppMediaTypeMovie
}


PpMouseActivation: dict = {
    1: k.mouse_activation_mouse_click,  # ppMouseClick
    2: k.mouse_activation_mouse_over,  # ppMouseOver
}


PpNumberedBulletStyle: dict = {
    0: k.ppBulletAlphaLCPeriod,  # ppBulletAlphaLCPeriod
    1: k.ppBulletAlphaUCPeriod,  # ppBulletAlphaUCPeriod
    2: k.ppBulletArabicParenRight,  # ppBulletArabicParenRight
    3: k.ppBulletArabicPeriod,  # ppBulletArabicPeriod
    4: k.ppBulletRomanLCParenBoth,  # ppBulletRomanLCParenBoth
    5: k.ppBulletRomanLCParenRight,  # ppBulletRomanLCParenRight
    6: k.ppBulletRomanLCPeriod,  # ppBulletRomanLCPeriod
    7: k.ppBulletRomanUCPeriod,  # ppBulletRomanUCPeriod
    8: k.ppBulletAlphaLCParenBoth,  # ppBulletAlphaLCParenBoth
    9: k.ppBulletAlphaLCParenRight,  # ppBulletAlphaLCParenRight
    10: k.ppBulletAlphaUCParenBoth,  # ppBulletAlphaUCParenBoth
    11: k.ppBulletAlphaUCParenRight,  # ppBulletAlphaUCParenRight
    12: k.ppBulletArabicParenBoth,  # ppBulletArabicParenBoth
    13: k.ppBulletArabicPlain,  # ppBulletArabicPlain
    14: k.ppBulletRomanUCParenBoth,  # ppBulletRomanUCParenBoth
    15: k.ppBulletRomanUCParenRight,  # ppBulletRomanUCParenRight
    26: k.ppBulletKanjiKoreanPlain,  # ppBulletKanjiKoreanPlain
    27: k.ppBulletKanjiKoreanPeriod,  # ppBulletKanjiKoreanPeriod
    28: k.ppBulletArabicDBPlain,  # ppBulletArabicDBPlain
}


PpParagraphAlignment: dict = {
    1: k.paragraph_align_left,  # ppAlignLeft
    2: k.paragraph_align_center,  # ppAlignCenter
    3: k.paragraph_align_right,  # ppAlignRight
    4: k.paragraph_align_justify,  # ppAlignJustify
    5: k.paragraph_align_distribute,  # ppAlignDistribute
}


PpPlaceholderType: dict = {
    1: k.placeholder_type_title_placeholder,  # ppPlaceholderTitle
    2: k.placeholder_type_body_placeholder,  # ppPlaceholderBody
    3: k.placeholder_type_center_title_placeholder,  # ppPlaceholderCenterTitle
    4: k.placeholder_type_subtitle_placeholder,  # ppPlaceholderSubtitle
    5: k.placeholder_type_vertical_title_placeholder,  # ppPlaceholderVerticalTitle
    6: k.placeholder_type_vertical_body_placeholder,  # ppPlaceholderVerticalBody
    7: k.placeholder_type_object_placeholder,  # ppPlaceholderObject
    8: k.placeholder_type_chart_placeholder,  # ppPlaceholderChart
    9: k.placeholder_type_bitmap_placeholder,  # ppPlaceholderBitmap
    10: k.placeholder_type_media_clip_placeholder,  # ppPlaceholderMediaClip
    11: k.placeholder_type_org_chart_placeholder,  # ppPlaceholderOrgChart
    12: k.placeholder_type_table_placeholder,  # ppPlaceholderTable
    13: k.placeholder_type_slide_number_placeholder,  # ppPlaceholderSlideNumber
    14: k.placeholder_type_header_placeholder,  # ppPlaceholderHeader
    15: k.placeholder_type_footer_placeholder,  # ppPlaceholderFooter
    16: k.placeholder_type_date_placeholder,  # ppPlaceholderDate
    17: k.placeholder_type_vertical_object_placeholder,  # ppPlaceholderVerticalObject
    18: k.placeholder_type_picture_placeholder,  # ppPlaceholderPicture
}


PpSaveAsFileType: dict = {
    1: k.save_as_presentation,  # ppSaveAsPresentation
    5: k.save_as_template,  # ppSaveAsTemplate
    6: k.save_as_RTF,  # ppSaveAsRTF
    7: k.save_as_show,  # ppSaveAsShow
    8: k.save_as_addIn,  # ppSaveAsAddIn
    11: k.save_as_default,  # ppSaveAsDefault
    16: k.save_as_GIF,  # ppSaveAsGIF
    17: k.save_as_JPG,  # ppSaveAsJPG
    18: k.save_as_PNG,  # ppSaveAsPNG
    19: k.save_as_BMP,  # ppSaveAsBMP
    21: k.save_as_TIF,  # ppSaveAsTIF
    24: k.save_as_Open_XML_presentation,  # ppSaveAsOpenXMLPresentation
    25: k.save_as_Open_XML_presentation_macro_enabled,  # ppSaveAsOpenXMLPresentationMacroEnabled
    26: k.save_as_Open_XML_template,  # ppSaveAsOpenXMLTemplate
    28: k.save_as_Open_XML_show,  # ppSaveAsOpenXMLShow
    31: k.save_as_Open_XML_theme,  # ppSaveAsOpenXMLTheme
    32: k.save_as_PDF,  # ppSaveAsPDF
}


PpSelectionType: dict = {
    0: k.selection_type_none,  # ppSelectionNone
    1: k.selection_type_slides,  # ppSelectionSlides
    2: k.selection_type_shapes,  # ppSelectionShapes
    3: k.selection_type_text,  # ppSelectionText
}


PpSlideLayout: dict = {
    1: k.slide_layout_title_slide,  # ppLayoutTitle
    2: k.slide_layout_text_slide,  # ppLayoutText
    3: k.slide_layout_two_column_text,  # ppLayoutTwoColumnText
    4: k.slide_layout_table,  # ppLayoutTable
    5: k.slide_layout_text_and_chart,  # ppLayoutTextAndChart
    6: k.slide_layout_chart_and_text,  # ppLayoutChartAndText
    7: k.slide_layout_orgchart,  # ppLayoutOrgchart
    8: k.slide_layout_chart,  # ppLayoutChart
    9: k.slide_layout_text_and_clipart,  # ppLayoutTextAndClipArt
    10: k.slide_layout_clipart_and_text,  # ppLayoutClipArtAndText
    11: k.slide_layout_title_only,  # ppLayoutTitleOnly
    12: k.slide_layout_blank,  # ppLayoutBlank
    13: k.slide_layout_text_and_object,  # ppLayoutTextAndObject
    14: k.slide_layout_object_and_text,  # ppLayoutObjectAndText
    15: k.slide_layout_large_object,  # ppLayoutLargeObject
    16: k.slide_layout_object,  # ppLayoutObject
    18: k.slide_layout_media_clip_and_text,  # ppLayoutMediaClipAndText
    19: k.slide_layout_object_over_text,  # ppLayoutObjectOverText
    20: k.slide_layout_text_over_object,  # ppLayoutTextOverObject
    21: k.slide_layout_text_and_two_objects,  # ppLayoutTextAndTwoObjects
    22: k.slide_layout_two_objects_and_text,  # ppLayoutTwoObjectsAndText
    23: k.slide_layout_two_objects_over_text,  # ppLayoutTwoObjectsOverText
    24: k.slide_layout_four_objects,  # ppLayoutFourObjects
    25: k.slide_layout_vertical_text,  # ppLayoutVerticalText
    26: k.slide_layout_clipart_and_vertical_text,  # ppLayoutClipArtAndVerticalText
    27: k.slide_layout_vertical_title_and_text,  # ppLayoutVerticalTitleAndText
    28: k.slide_layout_vertical_title_and_text_over_chart,  # ppLayoutVerticalTitleAndTextOverChart
    29: k.slide_layout_two_objects,  # ppLayoutTwoObjects
    30: k.slide_layout_object_and_two_objects,  # ppLayoutObjectAndTwoObjects
    31: k.slide_layout_two_objects_and_object,  # ppLayoutTwoObjectsAndObject
    32: k.slide_layout_custom,  # ppLayoutCustom
    33: k.slide_layout_section_header,  # ppLayoutSectionHeader
    34: k.slide_layout_comparison,  # ppLayoutComparison
    35: k.slide_layout_content_with_caption,  # ppLayoutContentWithCaption
    36: k.slide_layout_picture_with_caption,  # ppLayoutPictureWithCaption
}


PpSlideShowAdvanceMode: dict = {
    1: k.slide_show_advance_manual_advance,  # ppSlideShowManualAdvance
    2: k.slide_show_advance_use_slide_timings,  # ppSlideShowUseSlideTimings
}


PpSlideShowRangeType: dict = {
    1: k.slide_show_range_show_all,  # ppShowAll
    2: k.slide_show_range,  # ppShowSlideRange
    3: k.slide_show_range_named_slideshow,  # ppShowNamedSlideShow
}


PpSlideShowState: dict = {
    1: k.slide_show_state_running,  # ppSlideShowRunning
    2: k.slide_show_state_paused,  # ppSlideShowPaused
    3: k.slide_show_state_black_screen,  # ppSlideShowBlackScreen
    4: k.slide_show_state_white_screen,  # ppSlideShowWhiteScreen
    5: k.slide_show_state_done,  # ppSlideShowDone
}


PpSlideShowType: dict = {
    1: k.slide_show_type_speaker,  # ppShowTypeSpeaker
    2: k.slide_show_type_window,  # ppShowTypeWindow
    3: k.slide_show_type_kiosk,  # ppShowTypeKiosk
}


PpViewType: dict = {
    1: k.slide_view,  # ppViewSlide
    4: k.handout_master_view,  # ppViewHandoutMaster
    5: k.notes_master_view,  # ppViewNotesMaster
    6: k.outline_view,  # ppViewOutline
    7: k.slide_sorter_view,  # ppViewSlideSorter
    8: k.title_master_view,  # ppViewTitleMaster
    9: k.normal_view,  # ppViewNormal
    10: k.print_preview,  # ppViewPrintPreview
}


PpWindowState: dict = {
    1: k.window_normal,  # ppWindowNormal
    2: k.window_minimized,  # ppWindowMinimized
}
